tagFormat: '${version}'

verifyConditions:
  - path: &npm '@semantic-release/npm'
    pkgRoot: '.'
  - &gh '@semantic-release/github'

prepare:
  - '@semantic-release/changelog'
  - *npm
  - path: '@semantic-release/git'
    message: 'chore(release): ${nextRelease.version}'
    assets:
      - CHANGELOG.md
      - README.md
      - package.json
      - yarn.lock
  - path: &exec '@semantic-release/exec'
    cmd: yarn run rollup
  - path: *exec
    cmd: yarn run rollup:prop-types

publish:
  - path: *exec
    cmd: bash -c "cd dist/main && npm publish"
  - path: *exec
    cmd: bash -c "cd dist/prop-types && npm publish"
  - *gh

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
