name: Core
on:
  - push

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
          registry-url: https://npm.pkg.github.com/alorel
      - name: Set up yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install deps
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
        env:
          CI: 'true'
      - name: Build library
        run: yarn run rollup
      - name: Build prop-types
        run: yarn run rollup:prop-types
      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
